package com.atech.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Light Colors
val LightPrimary = Color(0xFF24389C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF3F51B5)
val LightOnPrimaryContainer = Color(0xFFCACFFF)
val LightInversePrimary = Color(0xFFBAC3FF)
val LightSecondary = Color(0xFF4D5A9C)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFABB7FF)
val LightOnSecondaryContainer = Color(0xFF394687)
val LightTertiary = Color(0xFF2F3891)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF4851AA)
val LightOnTertiaryContainer = Color(0xFFCBCEFF)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightBackground = Color(0xFFF9F9FE)
val LightOnBackground = Color(0xFF1A1C1F)
val LightSurface = Color(0xFFF9F9FE)
val LightOnSurface = Color(0xFF1A1C1F)
val LightSurfaceVariant = Color(0xFFE2E2E7)
val LightOnSurfaceVariant = Color(0xFF454652)
val LightOutline = Color(0xFF757684)
val LightOutlineVariant = Color(0xFFC5C5D4)
val LightInverseSurface = Color(0xFF2E3034)
val LightInverseOnSurface = Color(0xFFF0F0F5)
val LightSurfaceTint = Color(0xFF4355B9)
// Surface Container roles
val LightSurfaceDim = Color(0xFFD9DADE)
val LightSurfaceBright = Color(0xFFF9F9FE)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF3F3F8)
val LightSurfaceContainer = Color(0xFFEDEDF2)
val LightSurfaceContainerHigh = Color(0xFFE8E8ED)
val LightSurfaceContainerHighest = Color(0xFFE2E2E7)

// Dark Colors
val DarkPrimary = Color(0xFFBAC3FF)
val DarkOnPrimary = Color(0xFF08218A)
val DarkPrimaryContainer = Color(0xFF3F51B5)
val DarkOnPrimaryContainer = Color(0xFFCACFFF)
val DarkInversePrimary = Color(0xFF4355B9)
val DarkSecondary = Color(0xFFDCB8FF)
val DarkOnSecondary = Color(0xFF480081)
val DarkSecondaryContainer = Color(0xFF7701D0)
val DarkOnSecondaryContainer = Color(0xFFDCB7FF)
val DarkTertiary = Color(0xFFC5C5D8)
val DarkOnTertiary = Color(0xFF2E2F3E)
val DarkTertiaryContainer = Color(0xFF58596A)
val DarkOnTertiaryContainer = Color(0xFFD0D1E4)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF11131C)
val DarkOnBackground = Color(0xFFE1E1EF)
val DarkSurface = Color(0xFF11131C)
val DarkOnSurface = Color(0xFFE1E1EF)
val DarkSurfaceVariant = Color(0xFF32343E)
val DarkOnSurfaceVariant = Color(0xFFC5C5D4)
val DarkOutline = Color(0xFF8F909E)
val DarkOutlineVariant = Color(0xFF454652)
val DarkInverseSurface = Color(0xFFE1E1EF)
val DarkInverseOnSurface = Color(0xFF2E303A)
val DarkSurfaceTint = Color(0xFFBAC3FF)
// Surface Container roles
val DarkSurfaceDim = Color(0xFF11131C)
val DarkSurfaceBright = Color(0xFF373943)
val DarkSurfaceContainerLowest = Color(0xFF0C0E17)
val DarkSurfaceContainerLow = Color(0xFF191B24)
val DarkSurfaceContainer = Color(0xFF1D1F29)
val DarkSurfaceContainerHigh = Color(0xFF282933)
val DarkSurfaceContainerHighest = Color(0xFF32343E)
