package com.atech.currents.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Lumina Light Colors
val LuminaLightPrimary = Color(0xFF24389C)
val LuminaLightOnPrimary = Color(0xFFFFFFFF)
val LuminaLightPrimaryContainer = Color(0xFF3F51B5)
val LuminaLightOnPrimaryContainer = Color(0xFFCACFFF)
val LuminaLightInversePrimary = Color(0xFFBAC3FF)
val LuminaLightSecondary = Color(0xFF4D5A9C)
val LuminaLightOnSecondary = Color(0xFFFFFFFF)
val LuminaLightSecondaryContainer = Color(0xFFABB7FF)
val LuminaLightOnSecondaryContainer = Color(0xFF394687)
val LuminaLightTertiary = Color(0xFF2F3891)
val LuminaLightOnTertiary = Color(0xFFFFFFFF)
val LuminaLightTertiaryContainer = Color(0xFF4851AA)
val LuminaLightOnTertiaryContainer = Color(0xFFCBCEFF)
val LuminaLightError = Color(0xFFBA1A1A)
val LuminaLightOnError = Color(0xFFFFFFFF)
val LuminaLightErrorContainer = Color(0xFFFFDAD6)
val LuminaLightOnErrorContainer = Color(0xFF93000A)
val LuminaLightBackground = Color(0xFFF9F9FE)
val LuminaLightOnBackground = Color(0xFF1A1C1F)
val LuminaLightSurface = Color(0xFFF9F9FE)
val LuminaLightOnSurface = Color(0xFF1A1C1F)
val LuminaLightSurfaceVariant = Color(0xFFE2E2E7)
val LuminaLightOnSurfaceVariant = Color(0xFF454652)
val LuminaLightOutline = Color(0xFF757684)
val LuminaLightOutlineVariant = Color(0xFFC5C5D4)
val LuminaLightInverseSurface = Color(0xFF2E3034)
val LuminaLightInverseOnSurface = Color(0xFFF0F0F5)
val LuminaLightSurfaceTint = Color(0xFF4355B9)
// Surface Container roles
val LuminaLightSurfaceDim = Color(0xFFD9DADE)
val LuminaLightSurfaceBright = Color(0xFFF9F9FE)
val LuminaLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LuminaLightSurfaceContainerLow = Color(0xFFF3F3F8)
val LuminaLightSurfaceContainer = Color(0xFFEDEDF2)
val LuminaLightSurfaceContainerHigh = Color(0xFFE8E8ED)
val LuminaLightSurfaceContainerHighest = Color(0xFFE2E2E7)

// Lumina Tech Utility Colors (Dark)
val LuminaDarkPrimary = Color(0xFFBAC3FF)
val LuminaDarkOnPrimary = Color(0xFF08218A)
val LuminaDarkPrimaryContainer = Color(0xFF3F51B5)
val LuminaDarkOnPrimaryContainer = Color(0xFFCACFFF)
val LuminaDarkInversePrimary = Color(0xFF4355B9)
val LuminaDarkSecondary = Color(0xFFDCB8FF)
val LuminaDarkOnSecondary = Color(0xFF480081)
val LuminaDarkSecondaryContainer = Color(0xFF7701D0)
val LuminaDarkOnSecondaryContainer = Color(0xFFDCB7FF)
val LuminaDarkTertiary = Color(0xFFC5C5D8)
val LuminaDarkOnTertiary = Color(0xFF2E2F3E)
val LuminaDarkTertiaryContainer = Color(0xFF58596A)
val LuminaDarkOnTertiaryContainer = Color(0xFFD0D1E4)
val LuminaDarkError = Color(0xFFFFB4AB)
val LuminaDarkOnError = Color(0xFF690005)
val LuminaDarkErrorContainer = Color(0xFF93000A)
val LuminaDarkOnErrorContainer = Color(0xFFFFDAD6)
val LuminaDarkBackground = Color(0xFF11131C)
val LuminaDarkOnBackground = Color(0xFFE1E1EF)
val LuminaDarkSurface = Color(0xFF11131C)
val LuminaDarkOnSurface = Color(0xFFE1E1EF)
val LuminaDarkSurfaceVariant = Color(0xFF32343E)
val LuminaDarkOnSurfaceVariant = Color(0xFFC5C5D4)
val LuminaDarkOutline = Color(0xFF8F909E)
val LuminaDarkOutlineVariant = Color(0xFF454652)
val LuminaDarkInverseSurface = Color(0xFFE1E1EF)
val LuminaDarkInverseOnSurface = Color(0xFF2E303A)
val LuminaDarkSurfaceTint = Color(0xFFBAC3FF)
// Surface Container roles
val LuminaDarkSurfaceDim = Color(0xFF11131C)
val LuminaDarkSurfaceBright = Color(0xFF373943)
val LuminaDarkSurfaceContainerLowest = Color(0xFF0C0E17)
val LuminaDarkSurfaceContainerLow = Color(0xFF191B24)
val LuminaDarkSurfaceContainer = Color(0xFF1D1F29)
val LuminaDarkSurfaceContainerHigh = Color(0xFF282933)
val LuminaDarkSurfaceContainerHighest = Color(0xFF32343E)